### ISSUE TITLE
NIST vs SECP 

### ISSUE THREAD

**Issue by mcr** [DavidEGrayson/ruby_ecdsa#10]
nistp256.rb             
     secp256r1.rb   

As far as I can verify, these are two names for the same group.  
Ditto for the 192 and 521.
        http://www.secg.org/collateral/

no longer answers, being directed to certicom's web site.   I wonder if it wouldn't be better to just have one or the other in the source code base?

**Comment by DavidEGrayson** [comment]
Thanks for pointing this out.  I can't think of any particular changes I would want to make to the code in light of this information which would not be breaking changes.  Even just making one group be an alias for the other would be a breaking change because `param_a` and `name` of one of the groups would have to change.

**Comment by mcr** [comment]
Okay, reasonable.
